### PR TITLE
Control panel improvement

### PR DESCRIPTION
**Pull request by jhird11**

### CODE REVIEW

**Comment by jhird11** [comment]
Just letting you know @weijiewong1991 that we've added a new button to the control panel that might affect your work. Let me know if it's being a hassle and we can sort something out.

I've also asked @LGVal to create square versions of the icons that should sit a bit better in the control panel

**Comment by weijiewong1991** [comment]
Haven't done much today, mostly just catching up with the changes. I can probably update from master before continuing.

**Comment by jhird11** [comment]
Ah no worries! Just trying to keep people in the loop cos we have lot's of people working on different bits :) I'll try to keep the UI stuff unmodified for you from now on so we can avoid future hassle

**Comment by weijiewong1991** [comment]
Sensor info screen images still WIP, discussing with Gaby about the art direction.

**Comment by weijiewong1991** [comment]
https://uob.sharepoint.com/teams/grp-FARSCOPE-UKRASFestivalofRoboticsEvent/Shared%20Documents/Game-a-thon%20Prototype%20Weekend%201/Menu%20and%20UI%20Design/Temporary/Sensor_info_screen.JPG

Not the best image but we don't have a clear concept on what the robot actually looks like. I pieced together Gaby's broken robot model and the main menu image. Discussed with Gaby, we can properly model the robot if we have time after everything more important is done.

**Comment by weijiewong1991** [comment]
Alright, fixed up everything to be able to be merged back into master. Note that special actions buttons still clip at the top. I think the only solution is to reduce the size of the three extra buttons.

**Pull request merged**
